spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/root?schema=anime
    username: root
    password: root
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
